<?php

namespace App\Support;

/**
 * Daftar provinsi dan kabupaten/kota Indonesia.
 * Difokuskan pada area kebun PPTK (Jawa Barat) dengan data lengkap,
 * provinsi lain tersedia untuk fleksibilitas.
 *
 * ponytail: static array; if data grows or needs frequent updates, consider DB table.
 */
class ProvinceData
{
    public static function provinces(): array
    {
        return array_keys(self::all());
    }

    public static function cities(string $province): array
    {
        return self::all()[$province] ?? [];
    }

    public static function all(): array
    {
        return [
            'Jawa Barat' => [
                'Kab. Bandung',
                'Kab. Bandung Barat',
                'Kab. Bekasi',
                'Kab. Bogor',
                'Kab. Ciamis',
                'Kab. Cianjur',
                'Kab. Cirebon',
                'Kab. Garut',
                'Kab. Indramayu',
                'Kab. Karawang',
                'Kab. Kuningan',
                'Kab. Majalengka',
                'Kab. Pangandaran',
                'Kab. Purwakarta',
                'Kab. Subang',
                'Kab. Sukabumi',
                'Kab. Sumedang',
                'Kab. Tasikmalaya',
                'Kota Bandung',
                'Kota Bekasi',
                'Kota Bogor',
                'Kota Cimahi',
                'Kota Cirebon',
                'Kota Depok',
                'Kota Sukabumi',
                'Kota Tasikmalaya',
                'Kota Banjar',
            ],
            'Jawa Tengah' => [
                'Kab. Banjarnegara',
                'Kab. Banyumas',
                'Kab. Batang',
                'Kab. Blora',
                'Kab. Boyolali',
                'Kab. Brebes',
                'Kab. Cilacap',
                'Kab. Demak',
                'Kab. Grobogan',
                'Kab. Jepara',
                'Kab. Karanganyar',
                'Kab. Kebumen',
                'Kab. Kendal',
                'Kab. Klaten',
                'Kab. Kudus',
                'Kab. Magelang',
                'Kab. Pati',
                'Kab. Pekalongan',
                'Kab. Pemalang',
                'Kab. Purbalingga',
                'Kab. Purworejo',
                'Kab. Rembang',
                'Kab. Semarang',
                'Kab. Sragen',
                'Kab. Sukoharjo',
                'Kab. Tegal',
                'Kab. Temanggung',
                'Kab. Wonogiri',
                'Kab. Wonosobo',
                'Kota Magelang',
                'Kota Pekalongan',
                'Kota Salatiga',
                'Kota Semarang',
                'Kota Surakarta',
                'Kota Tegal',
            ],
            'Jawa Timur' => [
                'Kab. Bangkalan',
                'Kab. Banyuwangi',
                'Kab. Blitar',
                'Kab. Bojonegoro',
                'Kab. Bondowoso',
                'Kab. Gresik',
                'Kab. Jember',
                'Kab. Jombang',
                'Kab. Kediri',
                'Kab. Lamongan',
                'Kab. Lumajang',
                'Kab. Madiun',
                'Kab. Magetan',
                'Kab. Malang',
                'Kab. Mojokerto',
                'Kab. Nganjuk',
                'Kab. Ngawi',
                'Kab. Pacitan',
                'Kab. Pamekasan',
                'Kab. Pasuruan',
                'Kab. Ponorogo',
                'Kab. Probolinggo',
                'Kab. Sampang',
                'Kab. Sidoarjo',
                'Kab. Situbondo',
                'Kab. Sumenep',
                'Kab. Trenggalek',
                'Kab. Tuban',
                'Kab. Tulungagung',
                'Kota Batu',
                'Kota Blitar',
                'Kota Kediri',
                'Kota Madiun',
                'Kota Malang',
                'Kota Mojokerto',
                'Kota Pasuruan',
                'Kota Probolinggo',
                'Kota Surabaya',
            ],
            'DI Yogyakarta' => [
                'Kab. Bantul',
                'Kab. Gunungkidul',
                'Kab. Kulon Progo',
                'Kab. Sleman',
                'Kota Yogyakarta',
            ],
            'Banten' => [
                'Kab. Lebak',
                'Kab. Pandeglang',
                'Kab. Serang',
                'Kab. Tangerang',
                'Kota Cilegon',
                'Kota Serang',
                'Kota Tangerang',
                'Kota Tangerang Selatan',
            ],
            'DKI Jakarta' => [
                'Kota Jakarta Barat',
                'Kota Jakarta Pusat',
                'Kota Jakarta Selatan',
                'Kota Jakarta Timur',
                'Kota Jakarta Utara',
                'Kab. Kepulauan Seribu',
            ],
            'Sumatera Utara' => [
                'Kab. Asahan',
                'Kab. Batubara',
                'Kab. Dairi',
                'Kab. Deli Serdang',
                'Kab. Humbang Hasundutan',
                'Kab. Karo',
                'Kab. Labuhanbatu',
                'Kab. Langkat',
                'Kab. Mandailing Natal',
                'Kab. Nias',
                'Kab. Padang Lawas',
                'Kab. Simalungun',
                'Kab. Serdang Bedagai',
                'Kab. Tapanuli Selatan',
                'Kab. Tapanuli Tengah',
                'Kab. Tapanuli Utara',
                'Kab. Toba',
                'Kota Binjai',
                'Kota Gunungsitoli',
                'Kota Medan',
                'Kota Padangsidimpuan',
                'Kota Pematangsiantar',
                'Kota Sibolga',
                'Kota Tanjungbalai',
                'Kota Tebing Tinggi',
            ],
            'Sumatera Barat' => [
                'Kab. Agam',
                'Kab. Dharmasraya',
                'Kab. Kepulauan Mentawai',
                'Kab. Lima Puluh Kota',
                'Kab. Padang Pariaman',
                'Kab. Pasaman',
                'Kab. Pasaman Barat',
                'Kab. Pesisir Selatan',
                'Kab. Sijunjung',
                'Kab. Solok',
                'Kab. Solok Selatan',
                'Kab. Tanah Datar',
                'Kota Bukittinggi',
                'Kota Padang',
                'Kota Padang Panjang',
                'Kota Pariaman',
                'Kota Payakumbuh',
                'Kota Sawahlunto',
                'Kota Solok',
            ],
            'Kalimantan Barat' => [
                'Kab. Bengkayang',
                'Kab. Kapuas Hulu',
                'Kab. Kayong Utara',
                'Kab. Ketapang',
                'Kab. Kubu Raya',
                'Kab. Landak',
                'Kab. Melawi',
                'Kab. Mempawah',
                'Kab. Sambas',
                'Kab. Sanggau',
                'Kab. Sekadau',
                'Kab. Sintang',
                'Kota Pontianak',
                'Kota Singkawang',
            ],
            'Sulawesi Selatan' => [
                'Kab. Bantaeng',
                'Kab. Barru',
                'Kab. Bone',
                'Kab. Bulukumba',
                'Kab. Enrekang',
                'Kab. Gowa',
                'Kab. Jeneponto',
                'Kab. Kepulauan Selayar',
                'Kab. Luwu',
                'Kab. Luwu Timur',
                'Kab. Luwu Utara',
                'Kab. Maros',
                'Kab. Pangkajene dan Kepulauan',
                'Kab. Pinrang',
                'Kab. Sidenreng Rappang',
                'Kab. Sinjai',
                'Kab. Soppeng',
                'Kab. Takalar',
                'Kab. Tana Toraja',
                'Kab. Toraja Utara',
                'Kab. Wajo',
                'Kota Makassar',
                'Kota Palopo',
                'Kota Parepare',
            ],
        ];
    }
}
